name = "neten"
uuid = "c6317dd7-74d0-485e-9c25-1656c63b7b1d"
authors = ["Tyler Bradshaw"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
